# Use Nginx to serve the static built files
FROM nginx:alpine

# Copy the build output from the Jenkins workspace into Nginx's public folder
# Vite builds files into a folder named 'dist'
COPY dist /usr/share/nginx/html

# Expose port 80 for the web traffic
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]